### ISSUE TITLE
Roadmap 0.1.0+pre.v1: Синтаксис.

### ISSUE THREAD

**Issue by RubaXa** [RubaXa/xtpl#1]
- [x] **Базовый синтаксис**
  - [x] `!html` => `<!doctype html>`
  - [x] `img` => `<img/>`
  - [x] `p | text` => `<p>text</p>`
  - [x] `// comment` => `<!--comment-->`
  - [x] `.head.sticky` => `<div class="head sticky"></div>`
  - [x] `#user` => `<div id="user"></div>`
  - [x] `b#dot.small` => `<b id="dot" class="small"></div>`
  - [x] `img[src="..."]` => `<img src="..."/>`
  - [x] `img[src="..."][align="top"]` => `<img src="..." align="top"/>`
  - [x] `input[type="text" value="..."]` => `<input type="type" value="..."/>`
  - [x] `i.q + a[href=".."] | Link` => `<i class="q"></i><a href="...">Link</a>`
  - [x] `.parent > .child` => `<div class="parent"><div class="child"></div></div>`
  - [x] `.a-sibling + .b-sibling` => `<div class="a-sibling"></div><div class="b-sibling"></div>`

- [x] **Базовая работа с css-классами**
  - [x] `.cbx > .&__checkmark` => `<div class="cbx"><div class="cbx__checkmark"><div><div>`
  - [x] `.btn > %-hidden > .&-ico + .&-txt` => `<div class="btn"><div class="btn-hidden-ico"></div><div class="btn-hidden-txt"></div></div>`

- [x] **Продвинутая работа с классами**
```sass
// <a href="..." class="link is-active">foo</a>
a.link[href="..."] | foo
   class.is-active: attrs.bar
```

- [x] **Продвинутая работа с классами + nesting**
```sass
// <a href="..." class="link link_active">foo</a>
a.link[href="..."] | foo
   class.&_active: attrs.bar
```

- [x] **Интерполируй это**
  - [x] tagName: `${Math.random() > .5 ? "b" : "i"}.wow | !` => `<i class="wow">!</i>`
  - [x] #id: `#${Date.now()}` => `<div id="124325346"></div>`
  - [x] classes: `.btn-${type} | Send` => `<div class="btn-submit">Send</div>
  - [x] inline value: `input[value="${search}"]` => `<input value="xtpl"/>`
  - [x] text: `p | Hi, ${username}!` => `<p>Hi, RubaXa!</p>

- [x] **if / else if / else**
- [x] **for (item in data) / for ([key, item] in data)**

- [x] **Пробел: перед и/или после тега**
  - [x] перед: `i.q + a[<][href=".."] | Link` => `<i class="q"></i> <a href="...">Link</a>`
  - [x] после: `i[>].like + i.dislike` => `<i class="like"></i> <i class="dislike"></i>`
  - [x] до и после: `.foo + div[<>].bar + .qux` => `<div class="foo"></div> <div class="bar"></div>  <div class="qux"></div>`

- [x] **Многострочный текст**
```sass
.content |> фильм ужасов про психбольницу
я ехала домой романс
алло инкогнито проверить
баланс<|
```

- [x] **HTML Fragment**
```sass
.content > #| фильм <a href="...">ужасов</a> про психбольницу
я ехала домой <b>романс</b>
алло инкогнито проверить
баланс |#
```
