### ISSUE TITLE
Roadmap v0.2.0 / Custom elements

### ISSUE THREAD

**Issue by RubaXa** [RubaXa/xtpl#2]
- [ ] **DEFINE**:
  - [ ] `idCard = (name, age)` => `{type: "define", raw: {attrs: ["name", "age"], type: "parenthesis"}}`
  - [ ] `btn = [text,icon]` => `{type: "define", raw: {attrs: ["name", "icon"], type: "bracket"}}`

- [ ] **CALL**
  - [ ] `.foo -> idCard(Date.now())` => `{type: "call", raw: {args: ["Date.now()"]}}`

- [ ] **Элемент**
```sass
// Определяем
btn = [text,url]
  ${url ? "a" : "button"}.btn[href="${url}"] | ${text}

// Используем
btn[text="Subsctibe"]
btn[url="..." text="...]
```

- [ ] **Вставки / Слоты**
```sass
// Определяем элемент
page = [title,authUser]
  html
    head
        title | ${title}

        // Определяем начальное содержимое "выставки"
        scripts = ()
          script[src="/bundle/core.js"]

        // Вызываем "выставку"
        scripts()

        // (!!!) Определяем начальное содержимое "выставки" и сразу вызываем
        styleSheet()
           link[rel="stylesheet" href="/bundle/core.css"]
    body
       // Вызываем вставку в параметром
       .content > content(authUser.name)

// Используем элемент
page[title="Home"][authUser="${attrs.authUser}"]
  // Переопределяем и наследуем "вставку"
  scripts = ()
    super.scripts() + script[src="/bundle/home.js"]

  // Определяем содержимое страницы
  content = (username)
     h1 | Hi, ${username}!
```
