### ISSUE TITLE
Roadmap 0.1.0+pre.v2 / Перенести все preset из skeletik

### ISSUE THREAD

**Issue by RubaXa** [RubaXa/xtpl#4]
- [x] preset/expression -> syntax/expression
- [x] preset/xml -> syntax/xml
- [x] preset/xtpl -> syntax/xtpl
